/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as AvatarSelectRouteImport } from './routes/avatar-select'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as MultiplayerCodeRouteImport } from './routes/multiplayer.$code'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarSelectRoute = AvatarSelectRouteImport.update({
  id: '/avatar-select',
  path: '/avatar-select',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerCodeRoute = MultiplayerCodeRouteImport.update({
  id: '/multiplayer/$code',
  path: '/multiplayer/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar-select': typeof AvatarSelectRoute
  '/lobby': typeof LobbyRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/multiplayer/$code': typeof MultiplayerCodeRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar-select': typeof AvatarSelectRoute
  '/lobby': typeof LobbyRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/multiplayer/$code': typeof MultiplayerCodeRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar-select': typeof AvatarSelectRoute
  '/lobby': typeof LobbyRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/multiplayer/$code': typeof MultiplayerCodeRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar-select'
    | '/lobby'
    | '/play'
    | '/profile'
    | '/ranking'
    | '/result'
    | '/settings'
    | '/multiplayer/$code'
    | '/room/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar-select'
    | '/lobby'
    | '/play'
    | '/profile'
    | '/ranking'
    | '/result'
    | '/settings'
    | '/multiplayer/$code'
    | '/room/$code'
  id:
    | '__root__'
    | '/'
    | '/avatar-select'
    | '/lobby'
    | '/play'
    | '/profile'
    | '/ranking'
    | '/result'
    | '/settings'
    | '/multiplayer/$code'
    | '/room/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarSelectRoute: typeof AvatarSelectRoute
  LobbyRoute: typeof LobbyRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  ResultRoute: typeof ResultRoute
  SettingsRoute: typeof SettingsRoute
  MultiplayerCodeRoute: typeof MultiplayerCodeRoute
  RoomCodeRoute: typeof RoomCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar-select': {
      id: '/avatar-select'
      path: '/avatar-select'
      fullPath: '/avatar-select'
      preLoaderRoute: typeof AvatarSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer/$code': {
      id: '/multiplayer/$code'
      path: '/multiplayer/$code'
      fullPath: '/multiplayer/$code'
      preLoaderRoute: typeof MultiplayerCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarSelectRoute: AvatarSelectRoute,
  LobbyRoute: LobbyRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  ResultRoute: ResultRoute,
  SettingsRoute: SettingsRoute,
  MultiplayerCodeRoute: MultiplayerCodeRoute,
  RoomCodeRoute: RoomCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
